version: '3'
services:
  db:
    build: docker/database
    restart: always
    hostname: erapulus-db
    container_name: erapulus-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Q1W2e3r4
      - MSSQL_PID=Developer
    networks:
      - erapulus
    ports:
      - "1433:1433"

  app:
    build: docker/app
    restart: always
    hostname: erapulus-server
    container_name: erapulus-server
    volumes:
      - ./docker/app/erapulus-server.jar:/opt/app/erapulus-server.jar:ro
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=erapulus-db
    networks:
      - erapulus

networks:
  erapulus:
